[phases.setup]
nixPkgs = ["python3", "ffmpeg", "curl", "wget"]

[phases.install]
cmds = [
    "python -m pip install --break-system-packages -r requirements.txt",
    "python -m pip install --break-system-packages --upgrade yt-dlp"
]

[start]
cmd = "python main.py"